package drowntshirt;

import drowntshirt.model.Pembeli;
import javax.swing.JOptionPane;

/**
 *
 * @author syuhada
 */
public class Konfirmasi extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Konfirmasi.class.getName());
    
    private Pembeli data;
    
    public Konfirmasi(){}

    /**
     * Creates new form Konfirmasi
     */
    public Konfirmasi(Pembeli data) {
        this.data = data;
        initComponents();
        
        riwayatTxt.setVisible(false);
        ubahTxt.setVisible(false);
        btnUbah.setVisible(false);
        btnRiwayat.setVisible(false);
        txtRiwayatPesanan.setVisible(false);
        txtUbahPesanan.setVisible(false);
        
        getData();
        
    }
    
    public void getData(){
        
        tipeInput.setText(data.getTipe());
        namaInput.setText(data.getNama());
        alamatInput.setText(data.getAlamat());
        ukuranInput.setText(data.getUkuran()+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        tipeTxt = new javax.swing.JLabel();
        tipeInput = new javax.swing.JTextField();
        ukuranTxt = new javax.swing.JLabel();
        ukuranInput = new javax.swing.JTextField();
        namaTxt = new javax.swing.JLabel();
        namaInput = new javax.swing.JTextField();
        alamatTxt = new javax.swing.JLabel();
        alamatInput = new javax.swing.JTextField();
        beliTxt = new javax.swing.JLabel();
        btnBeli = new javax.swing.JButton();
        ubahTxt = new javax.swing.JLabel();
        btnUbah = new javax.swing.JButton();
        btnRiwayat = new javax.swing.JButton();
        riwayatTxt = new javax.swing.JLabel();
        txtRiwayatPesanan = new javax.swing.JLabel();
        txtUbahPesanan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(340, 437));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DROWN T-SHIRT");

        jButton4.setText("KELUAR");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton4))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 330, 70);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        tipeTxt.setText("Tipe baju");
        jPanel2.add(tipeTxt);
        tipeTxt.setBounds(40, 30, 90, 16);

        tipeInput.setEditable(false);
        tipeInput.addActionListener(this::tipeInput2ActionPerformed);
        jPanel2.add(tipeInput);
        tipeInput.setBounds(40, 50, 150, 30);

        ukuranTxt.setText("Ukuran");
        jPanel2.add(ukuranTxt);
        ukuranTxt.setBounds(40, 80, 90, 16);

        ukuranInput.setEditable(false);
        jPanel2.add(ukuranInput);
        ukuranInput.setBounds(40, 100, 150, 30);

        namaTxt.setText("Nama");
        jPanel2.add(namaTxt);
        namaTxt.setBounds(40, 130, 90, 16);

        namaInput.setEditable(false);
        namaInput.addActionListener(this::namaInputActionPerformed);
        jPanel2.add(namaInput);
        namaInput.setBounds(40, 150, 150, 30);

        alamatTxt.setText("Alamat");
        jPanel2.add(alamatTxt);
        alamatTxt.setBounds(40, 180, 90, 16);

        alamatInput.setEditable(false);
        jPanel2.add(alamatInput);
        alamatInput.setBounds(40, 200, 150, 30);

        beliTxt.setText("Lanjutkan membeli?");
        jPanel2.add(beliTxt);
        beliTxt.setBounds(40, 250, 180, 16);

        btnBeli.setText("BELI");
        btnBeli.addActionListener(this::btnBeliActionPerformed);
        jPanel2.add(btnBeli);
        btnBeli.setBounds(40, 270, 120, 23);

        ubahTxt.setText("Klik ubah jika ingin ");
        jPanel2.add(ubahTxt);
        ubahTxt.setBounds(210, 150, 110, 16);

        btnUbah.setText("UBAH");
        btnUbah.addActionListener(this::btnUbahActionPerformed);
        jPanel2.add(btnUbah);
        btnUbah.setBounds(210, 200, 100, 23);

        btnRiwayat.setText("RIWAYAT");
        btnRiwayat.addActionListener(this::btnRiwayatActionPerformed);
        jPanel2.add(btnRiwayat);
        btnRiwayat.setBounds(210, 100, 100, 23);

        riwayatTxt.setText("Klik untuk melihat");
        jPanel2.add(riwayatTxt);
        riwayatTxt.setBounds(210, 50, 100, 16);

        txtRiwayatPesanan.setText("riwayat pesanan");
        jPanel2.add(txtRiwayatPesanan);
        txtRiwayatPesanan.setBounds(210, 70, 90, 16);

        txtUbahPesanan.setText("mengubah pesanan");
        jPanel2.add(txtUbahPesanan);
        txtUbahPesanan.setBounds(210, 170, 110, 16);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 70, 330, 330);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRiwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRiwayatActionPerformed
        new RiwayatPembelian().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRiwayatActionPerformed

    private void btnBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeliActionPerformed
       /// Popup ucapan terima kasih
        JOptionPane.showMessageDialog(this,
                "Terima kasih sudah membeli!",
                "Sukses",
                JOptionPane.INFORMATION_MESSAGE);

    // Sembunyikan tombol Beli
        btnBeli.setVisible(false);
        beliTxt.setVisible(false);
        tipeTxt.setVisible(false);
        tipeInput.setVisible(false);
        namaTxt.setVisible(false);
        namaInput.setVisible(false);
        ukuranTxt.setVisible(false);
        ukuranInput.setVisible(false);
        alamatTxt.setVisible(false);
        alamatInput.setVisible(false);
        txtRiwayatPesanan.setVisible(false);
        txtUbahPesanan.setVisible(false);
        

    // Tampilkan tombol Ubah dan Riwayat
        ubahTxt.setVisible(true);
        riwayatTxt.setVisible(true);
        btnUbah.setVisible(true);
        btnRiwayat.setVisible(true);
        txtRiwayatPesanan.setVisible(true);
        txtUbahPesanan.setVisible(true);
    }//GEN-LAST:event_btnBeliActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        new ProsesPembelian().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUbahActionPerformed

    private void tipeInput2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipeInput2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipeInput2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JOptionPane.showMessageDialog(
            this,
            "Terimakasih sudah menggunakan aplikasi Drown T-Shirt",
            "Terima Kasih",
            JOptionPane.INFORMATION_MESSAGE
        );
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void namaInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Konfirmasi().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamatInput;
    private javax.swing.JLabel alamatTxt;
    private javax.swing.JLabel beliTxt;
    private javax.swing.JButton btnBeli;
    private javax.swing.JButton btnRiwayat;
    private javax.swing.JButton btnUbah;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField namaInput;
    private javax.swing.JLabel namaTxt;
    private javax.swing.JLabel riwayatTxt;
    private javax.swing.JTextField tipeInput;
    private javax.swing.JLabel tipeTxt;
    private javax.swing.JLabel txtRiwayatPesanan;
    private javax.swing.JLabel txtUbahPesanan;
    private javax.swing.JLabel ubahTxt;
    private javax.swing.JTextField ukuranInput;
    private javax.swing.JLabel ukuranTxt;
    // End of variables declaration//GEN-END:variables
}
