/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package drowntshirt;

import drownthsirt.model.Pembeli;
import javax.swing.JOptionPane;

/**
 *
 * @author farre
 */
public class Konfirmasi extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Konfirmasi.class.getName());

    /**
     * Creates new form Konfirmasi
     */
    public Konfirmasi() {
        initComponents();
        
        riwayatTxt.setVisible(false);
        ubahTxt.setVisible(false);
        btnUbah.setVisible(false);
        btnRiwayat.setVisible(false);
        
    }
    
    public void getData(){
        Pembeli obj = new Pembeli();
        
        tipeInput.setText(obj.getTipe());
        namaInput.setText(obj.getNama());
        alamatInput.setText(obj.getAlamat());
        ukuranInput.setText(obj.getUkuran()+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        tipeTxt = new javax.swing.JLabel();
        tipeInput = new javax.swing.JTextField();
        ukuranTxt = new javax.swing.JLabel();
        ukuranInput = new javax.swing.JTextField();
        namaTxt = new javax.swing.JLabel();
        namaInput = new javax.swing.JTextField();
        alamatTxt = new javax.swing.JLabel();
        alamatInput = new javax.swing.JTextField();
        beliTxt = new javax.swing.JLabel();
        btnBeli = new javax.swing.JButton();
        ubahTxt = new javax.swing.JLabel();
        btnUbah = new javax.swing.JButton();
        btnRiwayat = new javax.swing.JButton();
        riwayatTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(550, 420));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DROWN T-SHIRT");

        jButton4.setText("KELUAR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 246, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton4))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 530, 70);

        jPanel2.setLayout(null);

        tipeTxt.setText(" Tipe baju");
        jPanel2.add(tipeTxt);
        tipeTxt.setBounds(40, 30, 90, 18);

        tipeInput.addActionListener(this::tipeInputActionPerformed);
        jPanel2.add(tipeInput);
        tipeInput.setBounds(40, 50, 150, 24);

        ukuranTxt.setText("Ukuran");
        jPanel2.add(ukuranTxt);
        ukuranTxt.setBounds(40, 80, 90, 18);
        jPanel2.add(ukuranInput);
        ukuranInput.setBounds(40, 100, 150, 24);

        namaTxt.setText("Nama");
        jPanel2.add(namaTxt);
        namaTxt.setBounds(40, 130, 90, 18);
        jPanel2.add(namaInput);
        namaInput.setBounds(40, 150, 150, 24);

        alamatTxt.setText("Alamat");
        jPanel2.add(alamatTxt);
        alamatTxt.setBounds(40, 180, 90, 18);
        jPanel2.add(alamatInput);
        alamatInput.setBounds(40, 200, 150, 24);

        beliTxt.setText("Lanjutkan membeli?");
        jPanel2.add(beliTxt);
        beliTxt.setBounds(40, 250, 180, 18);

        btnBeli.setText("BELI");
        btnBeli.addActionListener(this::btnBeliActionPerformed);
        jPanel2.add(btnBeli);
        btnBeli.setBounds(70, 270, 120, 24);

        ubahTxt.setText("Klik ubah jika ingin mengubah pesanan");
        jPanel2.add(ubahTxt);
        ubahTxt.setBounds(200, 160, 280, 18);

        btnUbah.setText("UBAH");
        btnUbah.addActionListener(this::btnUbahActionPerformed);
        jPanel2.add(btnUbah);
        btnUbah.setBounds(290, 190, 72, 24);

        btnRiwayat.setText("RIWAYAT");
        btnRiwayat.addActionListener(this::btnRiwayatActionPerformed);
        jPanel2.add(btnRiwayat);
        btnRiwayat.setBounds(280, 100, 95, 24);

        riwayatTxt.setText("Klik untuk melihat riwayat pembelian");
        jPanel2.add(riwayatTxt);
        riwayatTxt.setBounds(220, 70, 234, 18);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 70, 530, 330);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRiwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRiwayatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRiwayatActionPerformed

    private void btnBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeliActionPerformed
       /// Popup ucapan terima kasih
        JOptionPane.showMessageDialog(this,
                "Terima kasih sudah membeli!",
                "Sukses",
                JOptionPane.INFORMATION_MESSAGE);

    // Sembunyikan tombol Beli
        btnBeli.setVisible(false);
        beliTxt.setVisible(false);
        tipeTxt.setVisible(false);
        tipeInput.setVisible(false);
        namaTxt.setVisible(false);
        namaInput.setVisible(false);
        ukuranTxt.setVisible(false);
        ukuranInput.setVisible(false);
        alamatTxt.setVisible(false);
        alamatInput.setVisible(false);
        

    // Tampilkan tombol Ubah dan Riwayat
        ubahTxt.setVisible(true);
        riwayatTxt.setVisible(true);
        btnUbah.setVisible(true);
        btnRiwayat.setVisible(true);
    }//GEN-LAST:event_btnBeliActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUbahActionPerformed

    private void tipeInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipeInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipeInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Konfirmasi().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamatInput;
    private javax.swing.JLabel alamatTxt;
    private javax.swing.JLabel beliTxt;
    private javax.swing.JButton btnBeli;
    private javax.swing.JButton btnRiwayat;
    private javax.swing.JButton btnUbah;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField namaInput;
    private javax.swing.JLabel namaTxt;
    private javax.swing.JLabel riwayatTxt;
    private javax.swing.JTextField tipeInput;
    private javax.swing.JLabel tipeTxt;
    private javax.swing.JLabel ubahTxt;
    private javax.swing.JTextField ukuranInput;
    private javax.swing.JLabel ukuranTxt;
    // End of variables declaration//GEN-END:variables
}
