package drowntshirt;

import drowntshirt.model.Pembeli;
import drowntshirt.service.KonfirmasiService;
import javax.swing.JOptionPane;

/**
 *
 * @author syuhada
 */
public class Konfirmasi extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Konfirmasi.class.getName());
    
    private Pembeli data;
    
    public Konfirmasi(){}

    /**
     * Creates new form Konfirmasi
     */
    public Konfirmasi(Pembeli data) {
        this.data = data;
        initComponents();
        
        riwayatTxt.setVisible(false);
        ubahTxt.setVisible(false);
        btnUbah.setVisible(false);
        btnRiwayat.setVisible(false);
        
        
        getData();
        
    }
    
    public void getData(){
        if(data.getId()==0){
            idInput.setText("-");
        }else {
            idInput.setText(String.valueOf(data.getId()));
        }
        tipeInput.setText(data.getTipe());
        namaInput.setText(data.getNama());
        alamatInput.setText(data.getAlamat());
        ukuranInput.setText(data.getUkuran());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        idTxt = new javax.swing.JLabel();
        idInput = new javax.swing.JTextField();
        ukuranTxt = new javax.swing.JLabel();
        ukuranInput = new javax.swing.JTextField();
        namaTxt = new javax.swing.JLabel();
        namaInput = new javax.swing.JTextField();
        alamatTxt = new javax.swing.JLabel();
        alamatInput = new javax.swing.JTextField();
        beliTxt = new javax.swing.JLabel();
        btnBeli = new javax.swing.JButton();
        ubahTxt = new javax.swing.JLabel();
        btnUbah = new javax.swing.JButton();
        btnRiwayat = new javax.swing.JButton();
        riwayatTxt = new javax.swing.JLabel();
        tipeInput = new javax.swing.JTextField();
        tipeTxt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(340, 437));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DROWN T-SHIRT");

        jButton4.setText("KELUAR");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 261, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4)
                    .addComponent(jLabel1))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 530, 70);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        idTxt.setText("ID");
        jPanel2.add(idTxt);
        idTxt.setBounds(20, 40, 90, 18);

        idInput.setEditable(false);
        idInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        idInput.addActionListener(this::idInput2ActionPerformed);
        jPanel2.add(idInput);
        idInput.setBounds(20, 60, 270, 32);

        ukuranTxt.setText("Ukuran");
        jPanel2.add(ukuranTxt);
        ukuranTxt.setBounds(20, 140, 90, 18);

        ukuranInput.setEditable(false);
        ukuranInput.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                ukuranInputComponentAdded(evt);
            }
        });
        jPanel2.add(ukuranInput);
        ukuranInput.setBounds(20, 160, 270, 32);

        namaTxt.setText("Nama");
        jPanel2.add(namaTxt);
        namaTxt.setBounds(20, 190, 90, 18);

        namaInput.setEditable(false);
        namaInput.addActionListener(this::namaInputActionPerformed);
        jPanel2.add(namaInput);
        namaInput.setBounds(20, 210, 270, 32);

        alamatTxt.setText("Alamat");
        jPanel2.add(alamatTxt);
        alamatTxt.setBounds(20, 240, 90, 18);

        alamatInput.setEditable(false);
        jPanel2.add(alamatInput);
        alamatInput.setBounds(20, 260, 270, 32);

        beliTxt.setText("Lanjutkan membeli?");
        jPanel2.add(beliTxt);
        beliTxt.setBounds(20, 310, 110, 18);

        btnBeli.setText("BELI");
        btnBeli.addActionListener(this::btnBeliActionPerformed);
        jPanel2.add(btnBeli);
        btnBeli.setBounds(20, 330, 120, 32);

        ubahTxt.setText("Klik ubah jika ingin pesanan anda");
        jPanel2.add(ubahTxt);
        ubahTxt.setBounds(310, 310, 180, 18);

        btnUbah.setText("UBAH");
        btnUbah.addActionListener(this::btnUbahActionPerformed);
        jPanel2.add(btnUbah);
        btnUbah.setBounds(350, 330, 100, 32);

        btnRiwayat.setText("RIWAYAT");
        btnRiwayat.addActionListener(this::btnRiwayatActionPerformed);
        jPanel2.add(btnRiwayat);
        btnRiwayat.setBounds(350, 270, 100, 32);

        riwayatTxt.setText("Klik untuk melihat riwayat pesanan anda");
        jPanel2.add(riwayatTxt);
        riwayatTxt.setBounds(300, 250, 220, 18);

        tipeInput.setEditable(false);
        tipeInput.addActionListener(this::tipeInput2ActionPerformed);
        jPanel2.add(tipeInput);
        tipeInput.setBounds(20, 110, 270, 32);

        tipeTxt.setText("Tipe baju");
        jPanel2.add(tipeTxt);
        tipeTxt.setBounds(20, 90, 90, 18);

        jLabel2.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel2.setText("MOHON KONFIRMASI PESANAN ANDA");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(90, 10, 350, 22);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 70, 530, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRiwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRiwayatActionPerformed
        new RiwayatPembelian(data).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRiwayatActionPerformed

    private void btnBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeliActionPerformed
       /// Popup ucapan terima kasih
        JOptionPane.showMessageDialog(this,
                "Terima kasih sudah membeli!",
                "Sukses",
                JOptionPane.INFORMATION_MESSAGE);

    // Sembunyikan tombol Beli
        btnBeli.setVisible(false);
        beliTxt.setVisible(false);
        idTxt.setVisible(false);
        idInput.setVisible(false);
        tipeTxt.setVisible(false);
        tipeInput.setVisible(false);
        namaTxt.setVisible(false);
        namaInput.setVisible(false);
        ukuranTxt.setVisible(false);
        ukuranInput.setVisible(false);
        alamatTxt.setVisible(false);
        alamatInput.setVisible(false);
        
        // mode create
        int mode = 0;
        if(!idInput.getText().equals("-")){
            // mode update
            mode = 1;
        }
        
        
        try {
            Pembeli pembeli = new Pembeli();
            KonfirmasiService service = new KonfirmasiService();
            if(mode==0){
                pembeli = service.insertObj(data);
            }else {
                pembeli = service.update(data);
            }
            

            if (pembeli!=null) {
                JOptionPane.showMessageDialog(this, "Berhasil disimpan!");
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menyimpan ke database");
            }
        } catch (Exception e) {
            System.err.println("error : "+e.getMessage());
        }
        

    // Tampilkan tombol Ubah dan Riwayat
        ubahTxt.setVisible(true);
        riwayatTxt.setVisible(true);
        btnUbah.setVisible(true);
        btnRiwayat.setVisible(true);
        
        
    }//GEN-LAST:event_btnBeliActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        new ProsesPembelian(data).setVisible(true);
//        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnUbahActionPerformed

    private void idInput2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idInput2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idInput2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JOptionPane.showMessageDialog(
            this,
            "Terimakasih sudah menggunakan aplikasi Drown T-Shirt",
            "Terima Kasih",
            JOptionPane.INFORMATION_MESSAGE
        );
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void namaInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaInputActionPerformed

    private void tipeInput2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipeInput2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipeInput2ActionPerformed

    private void ukuranInputComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_ukuranInputComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_ukuranInputComponentAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Konfirmasi().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamatInput;
    private javax.swing.JLabel alamatTxt;
    private javax.swing.JLabel beliTxt;
    private javax.swing.JButton btnBeli;
    private javax.swing.JButton btnRiwayat;
    private javax.swing.JButton btnUbah;
    private javax.swing.JTextField idInput;
    private javax.swing.JLabel idTxt;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField namaInput;
    private javax.swing.JLabel namaTxt;
    private javax.swing.JLabel riwayatTxt;
    private javax.swing.JTextField tipeInput;
    private javax.swing.JLabel tipeTxt;
    private javax.swing.JLabel ubahTxt;
    private javax.swing.JTextField ukuranInput;
    private javax.swing.JLabel ukuranTxt;
    // End of variables declaration//GEN-END:variables
}
